# -*- coding: utf-8 -*-
"""
Created on Tue May  7 15:47:06 2024

@author: melanie
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fenetre1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

class Interface_sac(object):
    
    def __init__(self, MainWindow, sac_pokemon):
        
        self.sac_pokemon = sac_pokemon
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(276, 70, 372, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 800, 500))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../data/img/combat/cadre.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(326, 105, 247, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        
        self.listWidget = QtWidgets.QListWidget(MainWindow)
        self.listWidget.setGeometry(QtCore.QRect(110, 250, 650, 330))
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setIconSize(QtCore.QSize(50, 50))
        
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        
        
        self.listWidget.setSelectionMode(QtWidgets.QListWidget.SingleSelection)
        
        
        self.pushButton_1 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_1.setGeometry(QtCore.QRect(250, 695, 150, 40))
        self.pushButton_1.setObjectName("push_button_1")
        
        
        self.pushButton_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 695, 150, 40))
        self.pushButton_2.setObjectName("push_button_2")
        
        self.pushButton_3 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(375, 745, 150, 40))
        self.pushButton_3.setObjectName("exit")
        
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
       
    
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)        
        
        
        
    def retranslateUi(self, MainWindow):
          
        
          
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Dialog", "Dialog"))
       
        self.label.setText(_translate("Dialog", "VOUS AVEZ OUVERT LE SAC !"))
        self.label_2.setText(_translate("Dialog", "CLIQUEZ SUR UN POKEMON"))
       
        self.pushButton_1.setText(_translate("Dialog", "Monter"))
        self.pushButton_2.setText(_translate("Dialog", "Descendre"))
        self.pushButton_3.setText(_translate("Dialog", "Fermer le sac"))
        self.update()
        
        
    def update(self) :
        _translate = QtCore.QCoreApplication.translate
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        
        list_pokemon = pd.read_csv(("../data/pokemon_first_gen.csv"), delimiter = ',')
        
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", str(self.sac_pokemon.objets[0].name)) + ", " + str(self.sac_pokemon.objets[0].type1) + ", " + str(self.sac_pokemon.objets[0].pv))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[0].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        
        
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", str(self.sac_pokemon.objets[1].name)) + ", " + str(self.sac_pokemon.objets[1].type1) + ", " + str(self.sac_pokemon.objets[1].pv))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[1].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
          
       
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", str(self.sac_pokemon.objets[2].name)) + ", " + str(self.sac_pokemon.objets[2].type1) + ", " + str(self.sac_pokemon.objets[2].pv))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[2].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        
       
        if len(self.sac_pokemon.objets) == 4 :
            
            item = self.listWidget.item(3)
            item.setText(_translate("Dialog", str(self.sac_pokemon.objets[3].name)) + ", " + str(self.sac_pokemon.objets[3].type1) + ", " + str(self.sac_pokemon.objets[3].pv))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[3].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            
        elif len(self.sac_pokemon.objets) == 5 :
            
            item = self.listWidget.item(3)
            item.setText(_translate("Dialog", str(self.sac_pokemon.objets[3].name)) + ", " + str(self.sac_pokemon.objets[3].type1) + ", " + str(self.sac_pokemon.objets[3].pv))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[3].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            
            item = self.listWidget.item(4)
            item.setText(_translate("Dialog", str(self.sac_pokemon.objets[4].name)) + ", " + str(self.sac_pokemon.objets[4].type1) + ", " + str(self.sac_pokemon.objets[4].pv))   
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[4].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
                
        elif len(self.sac_pokemon.objets) == 6 : 
            
            item = self.listWidget.item(3)
            item.setText(_translate("Dialog", str(self.sac_pokemon.objets[3].name)) + ", " + str(self.sac_pokemon.objets[3].type1) + ", " + str(self.sac_pokemon.objets[3].pv))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[3].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            
            item = self.listWidget.item(4)
            item.setText(_translate("Dialog", str(self.sac_pokemon.objets[4].name)) + ", " + str(self.sac_pokemon.objets[4].type1) + ", " + str(self.sac_pokemon.objets[4].pv))   
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[4].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            
            item = self.listWidget.item(5)
            item.setText(_translate("Dialog", str(self.sac_pokemon.objets[5].name)) + ", " + str(self.sac_pokemon.objets[5].type1) + ", " + str(self.sac_pokemon.objets[5].pv))   
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../data/sprites/face/" + str(list(list_pokemon.Name).index(str(self.sac_pokemon.objets[5].name))+1) + ".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)        
      
      
        self.listWidget.setSortingEnabled(__sortingEnabled)
          
          
    def show(self):
        self.update()
        self.listWidget.update()
        self.label.show()
        self.label_2.show()
        self.label_4.show()
        self.listWidget.show()
        self.pushButton_1.show()
        self.pushButton_2.show()
        self.pushButton_3.show()
        
        
        
    def hide(self):
        
        self.label.hide()
        self.label_2.hide()
        self.label_4.hide()
        self.listWidget.hide()
        self.pushButton_1.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        
        


        
        


